global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "tax-web"
    static_configs:
      - targets: ["tax-web:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]