name: Go CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kiselevos/tax-ci:v1.2.0

    env:
      GOFLAGS: "-buildvcs=false"   # Глобально для всех make-команд (отключить VCS stamping)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # git-метаданные доступны

      - name: Generate protobuf files
        run: make codegen

      - name: Lint
        run: make lint-all
      
      - name: Check formatting
        run: make check-fmt

      - name: Build project
        run: make build

      - name: Run tests
        run: make test-all
