server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # 👇 проксирование всех gRPC-web запросов
    location /api/ {
        proxy_pass http://backend:8081/; 
        proxy_http_version 1.1;

        proxy_request_buffering off;
        proxy_buffering off;

        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;

        # CORS
        add_header Access-Control-Allow-Origin * always;
        add_header Access-Control-Allow-Headers "Content-Type, X-Grpc-Web, Authorization" always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;

        if ($request_method = OPTIONS) {
            add_header Content-Length 0;
            add_header Content-Type text/plain;
            return 204;
        }
    }
}
